<TimeManager>:
    days_list: days_list

    MDBoxLayout:
        orientation: 'vertical'

        MDToolbar:
            title: "Time Manager"
            md_bg_color: [.8, 0, 0, .7]
            elevation: 50
            right_action_items: [["door", lambda x: root.go_back()]]

        BoxLayout:
            size_hint: 1, 1

            ScrollView:

                bar_color: 0, 0, 255, 1
                bar_width: 12

                MDList:
                    id: days_list
